<?php
include '../includes/TCPDF-main/tcpdf.php';
include '../Records/fetch_requests.php';
include '../includes/db.php';

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Deployed Assets');
$pdf->SetSubject('Deployed Assets PDF');
$pdf->SetKeywords('TCPDF, PDF, deployed, assets');

// Set default header data
$pdf->SetHeaderData('', 0, 'Deployed Assets Report', 'Generated by System');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page with landscape orientation
$pdf->AddPage('L');

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add a title
$pdf->Cell(0, 10, 'Deployed Assets', 0, 1, 'C');

// Create the table
$html = '<table border="1" cellpadding="4">
    <thead>
        <tr>
            <th style="background-color:#f2f2f2;">Asset ID</th>
            <th style="background-color:#f2f2f2;">Asset Name</th>
            <th style="background-color:#f2f2f2;">Brand</th>
            <th style="background-color:#f2f2f2;">Model</th>
            <th style="background-color:#f2f2f2;">Deployed to</th>
            <th style="background-color:#f2f2f2;">Room Name</th>
            <th style="background-color:#f2f2f2;">QR Code</th>
            <th style="background-color:#f2f2f2;">Status</th>
        </tr>
    </thead>
    <tbody>';

foreach ($disposed as $asset) {
    $html .= '<tr>
        <td>' . htmlspecialchars($asset['invID'] ?? 'N/A') . '</td>
        <td>' . htmlspecialchars($asset['inventoryName'] ?? 'N/A') . '</td>
        <td>' . htmlspecialchars($asset['brandName'] ?? 'N/A') . '</td>
        <td>' . htmlspecialchars($asset['modelName'] ?? 'N/A') . '</td>
        <td>' . htmlspecialchars(($asset['lastName'] ?? '') . ', ' . ($asset['firstName'] ?? '')) . '</td>
        <td>' . htmlspecialchars($asset['roomName'] ?? 'N/A') . '</td>
        <td><img src="' . ($asset['qrcode'] ? 'data:image/png;base64,' . base64_encode($asset['qrcode']) : 'default-qr.png') . '" alt="QR Code" class="w-16 h-16 mx-auto"></td>
        <td>' . htmlspecialchars($asset['status'] ?? 'N/A') . '</td>
    </tr>';
}

$html .= '</tbody></table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('deployed_assets.pdf', 'I');
?>