<?php

session_start();
require 'includes/db.php'; // Include DB connection
require 'includes/TCPDF-main/tcpdf.php'; // Include TCPDF library

if (!isset($_POST['transfer'])) {
    header('Location: Records/view_request.php');
    exit;
}

$request_id = $_POST['transfer'];

try {
    $sql = "SELECT th.*, 
    pic.name AS person_in_charge_name, 
    r.name AS room_name,
    rm.name AS currentRoom,
    ass.*
FROM transfer_history th
LEFT JOIN asset_records ass ON th.asset_records_id = ass.id
LEFT JOIN persons_in_charge pic ON th.person_in_charge_id = pic.id
LEFT JOIN rooms rm ON ass.room_id = rm.id
LEFT JOIN rooms r ON th.room_id = r.id   
WHERE th.status = 'Approved' AND th.id = '$request_id'  ";

    
    $stmt = $conn->prepare($sql);
    $stmt->execute();

    $requests = $stmt->fetchAll(PDO::FETCH_ASSOC); // Fetch all records

    // Extend the TCPDF class to add a custom footer
    class MYPDF extends TCPDF {
        public function Footer() {
            $this->SetY(-15);
            $this->SetFont('helvetica', 'I', 8);
            $this->Cell(0, 10, 'This is a system-generated document, Generated by:', 0, 1, 'C');
            $logo = 'images/SYSTEM LOGO.png'; 
            $this->Image($logo, $this->GetX() + 130, $this->GetY() - 10, 20);
        }
    }

    // Create new PDF document
    $pdf = new MYPDF();
    $pdf->AddPage();
    $pdf->SetFont('helvetica', '', 12);

    $logoLeft = 'images/OSJLOGO.png'; // Replace with the actual path to the left logo
    $logoRight = 'images/DAZSMALOGO.png'; // Replace with the actual path to the right logo

    $pdf->Image($logoLeft, 10, 10, 30); // Adjust the x, y, and size as necessary
    $pdf->Image($logoRight, 170, 10, 30); // Adjust the x, y, and size as necessary

    $pdf->Cell(0, 15, 'Don Antonio De Zuzuarregui Sr. Memorial Academy Incorporated', 0, 1, 'C');
    $pdf->Cell(0, 0, 'Brgy. Inarawan, Antipolo City', 0, 1, 'C');
    $pdf->Ln(8); 
    
    $pdf->SetFont('helvetica', 'B', 15);
    $pdf->Cell(0, 10, 'TRANSFER FORM', 0, 1, 'C');
    $pdf->Ln(8);

    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 10, 'Date of Request: ' , 0, 1);
    $pdf->Cell(0, 10, 'Transfer By: ' , 0, 1);
    $pdf->Ln(5);

    // Asset details header
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->Cell(170, 10, 'Asset Details', 1, 1);
    $pdf->Cell(30, 10, 'Items', 1);
    $pdf->Cell(40, 10, 'Brand', 1);
    $pdf->Cell(30, 10, 'Specs', 1);
    $pdf->Cell(40, 10, 'Current Room', 1);
    $pdf->Cell(30, 10, 'New Room', 1);
    $pdf->Ln();

    // Loop through the data and populate asset rows
    foreach ($requests as $row) {
        $pdf->Cell(30, 10, htmlspecialchars($row['unique_name']), 1); // Assuming item_name is available
        $pdf->Cell(40, 10, htmlspecialchars($row['model']), 1); // Assuming brand is available
        $pdf->Cell(30, 10, htmlspecialchars($row['specs']), 1); // Assuming specs are available
        $pdf->Cell(40, 10, htmlspecialchars($row['currentRoom']), 1); // Assuming current room
        $pdf->Cell(30, 10, htmlspecialchars($row['room_name']), 1); // New room
        $pdf->Ln();
    }

    $pdf->Ln(10);

    // Recieving Department
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->Cell(170, 10, 'Recieving Department', 1, 1);
    
    $pdf->Cell(56, 10, 'Room', 1);
    $pdf->Cell(56, 10, 'Person in charge', 1);
    $pdf->Cell(58, 10, 'Date Received', 1);
    $pdf->Ln();

    // Loop for receiving department details
    foreach ($requests as $row) {
        $pdf->Cell(56, 10, htmlspecialchars($row['room_name']), 1);
        $pdf->Cell(56, 10, htmlspecialchars($row['person_in_charge_name']), 1);
        $pdf->Cell(58, 10, htmlspecialchars($row['transferred_date']), 1); // Assuming transferred_date exists
        $pdf->Ln();
    }

    $pdf->Ln(20);

    // Footer Endorsements
    $pdf->SetFont('helvetica', 'B', 6);
    $pdf->MultiCell(30, 20, 'Endorsed by: 
    Mr. Osmond B. Baylen
    Principal ', 1, 'L', false, 0);
    $pdf->MultiCell(40, 20, 'Checked By: 
    Ms. Anna Liza M. Bernales
    Accounting Assistant ', 1, 'L', false, 0);
    $pdf->MultiCell(30, 20, 'Recommended By: 
    Rev. Fr. Gerardo I. Yabyabin, OSJ
    Treasurer ', 1, 'L', false, 0);
    $pdf->MultiCell(30, 20, 'Approved By: 
    Rev. Fr. Erwin B. Aguilar, OSJ
    Director', 1, 'L', false, 0);
    $pdf->MultiCell(40, 20, 'Released By: 
    Mrs. Lorna T. Villagracia
    Cashier ', 1, 'L', false, 1);

    // Output PDF
    $pdf->Output('Requisition_For.pdf', 'I');
    exit;

} catch (PDOException $e) {
    echo "Error: " . $e->getMessage();
}
?>
